name: Generate README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate README
        run: |
          echo "# Grub Theme Previews" > README.md
          echo "" >> README.md
          for file in Preview/*.{png,jpg}; do
            theme_name=$(basename "$file" | sed 's/\.[^.]*$//')
            echo "## $theme_name" >> README.md
            echo "![$theme_name](./$file)" >> README.md
            echo "" >> README.md
          done
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update README with theme previews"
          git push
