name: Daily README Refresh

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "0xRad1ant"
          git config --global user.email "anshulchoudhary227@gmail.com"

      - name: Update README
        run: |
          # Create a backup of the current README
          cp README.md README.bak

          # Check if the badges are already present
          if ! grep -q "# Grub Theme Update" README.md; then
            # Write the badges at the top of the README
            echo -e "# Grub Theme Update\n" > README.md
            echo -e "![Stars](https://img.shields.io/github/stars/0xRad1ant/Grub-Themes?style=social)" >> README.md
            echo -e "![Last Commit](https://img.shields.io/github/last-commit/0xRad1ant/Grub-Themes)" >> README.md
            echo -e "![Issues](https://img.shields.io/github/issues/0xRad1ant/Grub-Themes)" >> README.md
            echo -e "![License](https://img.shields.io/github/license/0xRad1ant/Grub-Themes)\n" >> README.md
          fi

          # Append the rest of the README content, ensuring to skip the first line if it contains the header
          tail -n +2 README.bak >> README.md

          # Clean up backup file
          rm README.bak

      - name: Commit and Push Changes
        run: |
          git add README.md
          git commit -m "Daily README refresh with badges" || echo "No changes to commit"
          git push
